### PR TITLE
Location maps

### PR DESCRIPTION
**Pull request by lGruenzweilHTL**
Finished adding maps for every pokemon

### CODE REVIEW

**Comment by lGruenzweilHTL** [comment]
@l-marazovic-HTL please review the changes to your manually added descriptions before approving this pr.

**Comment by lGruenzweilHTL** [comment]
@l-marazovic-HTL please review

**Comment by l-marazovic-HTL** [comment]
The most Location are right and some have to be fixed (for example snorlax or butterfree)

**Comment by lGruenzweilHTL** [comment]
I have already tracked down the bug and will try to fix it right away

**Comment by lGruenzweilHTL** [comment]
Fixed in [this commit](https://github.com/lGruenzweilHTL/WMC-Pokedex/pull/9/commits/8be68a0acc0d50deb74001079ff9575a6e8a7bb2)!

**Pull request merged**
